-- ==============================================================================
-- STP STAGE 2: FEATURE ENGINEERING & RESISTANCE SIGNALS
-- Schema Version: v2.0.0
-- Governance: M11-M22 Compliant
-- Prerequisite: Stage 1 tables must exist
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Metadata & Definitions (M18)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stp_signal_definitions (
    signal_name TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    unit TEXT,
    interpretation_guidance TEXT,
    limitations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.stp_signal_definitions IS 'M18: Registry of all Stage 2 signal definitions for interpretability.';

-- Seed common definitions
INSERT INTO public.stp_signal_definitions (signal_name, description, unit, interpretation_guidance, limitations)
VALUES 
('resistance_rate', 'Proportion of tested isolates that are resistant', 'Proportion (0-1)', 'Calculated as R / (S + I + R). I is included in denominator.', 'Dependent on testing volume'),
('exposure_density', 'Antibiotic pressure metric', 'Tests/Isolate', 'Average number of antibiotics tested per isolate', 'Proxy for varying testing protocols'),
('shannon_index', 'Diversity of antibiotic exposure', 'Entropy Score', 'Higher values indicate more diverse testing patterns', 'Biased by formulary changes'),
('rolling_slope', 'Linear trend of resistance over time', 'Rate Change/Week', 'Positive = increasing resistance, Negative = decreasing', 'Sensitive to outliers in short windows');


-- ------------------------------------------------------------------------------
-- 2. Surveillance Tables (M11, M12, M15, M16, M21, M22)
-- ------------------------------------------------------------------------------

-- Weekly Resistance Rates
CREATE TABLE IF NOT EXISTS public.stp_resistance_rates_weekly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organism TEXT NOT NULL,
    antibiotic TEXT NOT NULL,
    ward TEXT NOT NULL,
    week_start DATE NOT NULL,
    
    -- Metrics
    resistance_rate FLOAT, -- Nullable for zero denominators (M22)
    
    -- M11/M15/M21: Denominator Transparency
    tested_count INT NOT NULL DEFAULT 0, -- Excludes NA
    susceptible_count INT NOT NULL DEFAULT 0,
    intermediate_count INT NOT NULL DEFAULT 0,
    resistant_count INT NOT NULL DEFAULT 0,
    
    -- M16: Partial Window Handling
    is_partial_window BOOLEAN DEFAULT FALSE,
    coverage_days INT DEFAULT 7,
    
    -- M12/M22: Stability & Suppression
    is_stable BOOLEAN DEFAULT TRUE,
    suppression_reason TEXT, -- 'LOW_SAMPLE_SIZE', etc.
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Unique constraint for upsert
    CONSTRAINT uq_stp_weekly_rates UNIQUE (organism, antibiotic, ward, week_start)
);

CREATE INDEX idx_stp_weekly_rates_dim ON public.stp_resistance_rates_weekly(organism, antibiotic, ward);
CREATE INDEX idx_stp_weekly_rates_time ON public.stp_resistance_rates_weekly(week_start);


-- Monthly Resistance Rates
CREATE TABLE IF NOT EXISTS public.stp_resistance_rates_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organism TEXT NOT NULL,
    antibiotic TEXT NOT NULL,
    ward TEXT NOT NULL,
    month_start DATE NOT NULL,
    
    resistance_rate FLOAT,
    
    tested_count INT NOT NULL DEFAULT 0,
    susceptible_count INT NOT NULL DEFAULT 0,
    intermediate_count INT NOT NULL DEFAULT 0,
    resistant_count INT NOT NULL DEFAULT 0,
    
    is_partial_window BOOLEAN DEFAULT FALSE,
    coverage_days INT, -- Number of days covered in the month
    
    is_stable BOOLEAN DEFAULT TRUE,
    suppression_reason TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT uq_stp_monthly_rates UNIQUE (organism, antibiotic, ward, month_start)
);

CREATE INDEX idx_stp_monthly_rates_dim ON public.stp_resistance_rates_monthly(organism, antibiotic, ward);
CREATE INDEX idx_stp_monthly_rates_time ON public.stp_resistance_rates_monthly(month_start);


-- ------------------------------------------------------------------------------
-- 3. Ward Profiles & Pressure (M17)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stp_ward_resistance_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward TEXT NOT NULL,
    organism TEXT NOT NULL,
    antibiotic TEXT NOT NULL,
    
    mean_resistance FLOAT,
    std_resistance FLOAT,
    coverage_percent FLOAT, -- % of isolates in this ward tested for this abx
    
    observation_window_start DATE,
    observation_window_end DATE,
    
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT uq_stp_ward_profile UNIQUE (ward, organism, antibiotic)
);


CREATE TABLE IF NOT EXISTS public.stp_antibiotic_pressure_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward TEXT NOT NULL,
    time_window_start DATE NOT NULL,
    time_window_type TEXT NOT NULL CHECK (time_window_type IN ('weekly', 'monthly')),
    
    exposure_density FLOAT, -- tests per isolate
    shannon_index FLOAT,
    simpson_index FLOAT,
    
    -- M17: Availability Bias Control
    excluded_antibiotics TEXT[], -- List of abx excluded due to low coverage
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT uq_stp_pressure UNIQUE (ward, time_window_start, time_window_type)
);


-- ------------------------------------------------------------------------------
-- 4. Temporal Trends
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stp_temporal_trend_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organism TEXT NOT NULL,
    antibiotic TEXT NOT NULL,
    ward TEXT NOT NULL,
    week_start DATE NOT NULL,
    
    rolling_slope FLOAT, -- 12-week rolling slope
    week_over_week_delta FLOAT,
    volatility FLOAT, -- Rolling std dev
    
    change_point_flag BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT uq_stp_trends UNIQUE (organism, antibiotic, ward, week_start)
);


-- ------------------------------------------------------------------------------
-- 5. Feature Store (M14, M19)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stp_stage2_feature_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Dimensions
    organism TEXT NOT NULL,
    antibiotic TEXT NOT NULL,
    ward TEXT NOT NULL,
    week_start DATE NOT NULL,
    
    -- Features (Join of all signals)
    resistance_rate FLOAT,
    tested_count INT,
    
    trend_slope FLOAT,
    volatility FLOAT,
    
    exposure_density FLOAT,
    shannon_index FLOAT,
    
    -- Governance Flags
    is_stable BOOLEAN,
    is_partial_window BOOLEAN,
    
    -- M19: Versioning & Freeze
    stage2_version TEXT NOT NULL,
    derived_from_stage1_version TEXT NOT NULL,
    is_frozen BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT uq_stp_feature_store UNIQUE (organism, antibiotic, ward, week_start, stage2_version)
);

-- Index for ML retrieval
CREATE INDEX idx_stp_feature_store_fetch ON public.stp_stage2_feature_store(stage2_version, week_start);


-- ------------------------------------------------------------------------------
-- 6. Row Level Security (Stage 1 Read-Only Enforcement)
-- ------------------------------------------------------------------------------

-- Enable RLS
ALTER TABLE public.stp_signal_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_resistance_rates_weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_resistance_rates_monthly ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_ward_resistance_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_antibiotic_pressure_index ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_temporal_trend_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stp_stage2_feature_store ENABLE ROW LEVEL SECURITY;

-- Read policies (Public/Authenticated read)
CREATE POLICY "Public read access for signal definitions" ON public.stp_signal_definitions FOR SELECT USING (true);
CREATE POLICY "Authenticated read access for rates" ON public.stp_resistance_rates_weekly FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read access for monthly rates" ON public.stp_resistance_rates_monthly FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read access for ward profiles" ON public.stp_ward_resistance_profile FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read access for pressure" ON public.stp_antibiotic_pressure_index FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read access for trends" ON public.stp_temporal_trend_signals FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read access for feature store" ON public.stp_stage2_feature_store FOR SELECT TO authenticated USING (true);

-- Write policies (Service Role only - no direct user writes)
-- This enforces that only the pipeline (running as service_role) can write.
